esmnext/esmx

packages/rspack-module-link-plugin/src/config.ts
packages/rspack-module-link-plugin/src/entry.test.ts
packages/rspack-module-link-plugin/src/entry.ts
packages/rspack-module-link-plugin/src/index.ts
packages/rspack-module-link-plugin/src/parse.test.ts
packages/rspack-module-link-plugin/src/parse.ts
packages/rspack-module-link-plugin/src/types.ts

Add support for injecting pre-entry files into each entry point in the rspack-module-link-plugin.
- Add `preEntries` field to `ModuleLinkPluginOptions`
- Modify entry initialization to inject pre-entry files
- Add test coverage for entry configuration
- Added unit tests for all new functionality
- Tested both development and production configurations
- Verified preservation of existing configuration values
Closes #103

feat(rspack-module-link-plugin): add preEntries support

---

package.json
packages/class-state/tsconfig.json
packages/core/tsconfig.json
packages/fetch/tsconfig.json
packages/import/tsconfig.json
packages/lint/tsconfig.json
packages/router-vue/tsconfig.json
packages/router/tsconfig.json
packages/rspack-module-link-plugin/tsconfig.json
packages/rspack-vue/tsconfig.json
packages/rspack/tsconfig.json
pnpm-lock.yaml

- Update lint-staged to 16.1.2
- Remove lint-staged from local dependencies
- Update tsconfig files for better type checking
- Fixed micromatch ReDoS vulnerability by updating dependencies
- Improved project security by removing unnecessary local dependencies
- Verified all git hooks work correctly
- Confirmed no breaking changes in dependency updates

chore: update dependencies and fix security vulnerabilities

---

packages/router-vue/src/use.ts
packages/router/src/router.ts
packages/router/src/util.ts

1. The  hook in router-vue package doesn't properly update when the current route changes
2. Parameter names in router utils aren't descriptive or consistent
This PR includes two improvements:
1. **RouterLink reactivity enhancement**:
- Added route dependency to useLink computed property
- This ensures router links refresh when the route changes
- Fixed reactive updates without requiring manual refreshes
2. **Parameter naming consistency**:
- Renamed parameters in isRouteMatched function:
- route1 → fromRoute
- route2 → toRoute
- Updated corresponding JSDoc comments
- Made similar changes to Router class for consistency
- Manually verified the RouterLink component properly updates when route changes
- All existing functionality works as expected
- No regressions identified

fix(router): improve router-link reactivity and parameter naming

---

packages/rspack-module-link-plugin/src/external.test.ts
packages/rspack-module-link-plugin/src/external.ts

This PR addresses a critical issue in the  module where external module linking was not working correctly in certain scenarios.
- Refactored  function to use a more reliable state management approach
- Extracted core functionality into a reusable  function with proper initialization and matching logic
- Added comprehensive unit tests to ensure reliability and prevent regressions
- Fixed potential race conditions in module resolution
- More robust module linking across different environments
- Better handling of path resolution and module identification
- Improved maintainability with clear separation of concerns
- Complete test coverage for the external module linking functionality
This fix ensures that module dependencies are correctly resolved and externalized, which is essential for …

Fix module linking issues in rspack-module-link-plugin

---

packages/core/src/utils/import-map.test.ts
packages/core/src/utils/import-map.ts

When processing the ESM import map, encountering legacy build artifacts (where exportItem is a string) causes application exceptions.
1. Added detection for cases where  is a string in 
2. When detecting legacy format, throws a clear error message prompting users to upgrade dependencies and rebuild/redeploy
3. Added corresponding test cases to verify error handling logic
Added test cases verifying that when incompatible legacy formats are encountered, appropriate errors are thrown with clear messages.

fix(core): handle incompatible legacy manifest format

---

packages/rspack/src/app.ts

After PR #121 optimized the resource output directory structure by moving export modules to the `exports/` directory, the application startup file was not correctly updated to reference this new path. This caused built applications to fail when starting.
Updated the startup file generation in the `rewriteBuild` function to correctly reference the new export module path:
```diff
- const options = await import('./node/src/entry.node.mjs').then(
+ const options = await import('./node/exports/src/entry.node.mjs').then(
```
This change ensures the application correctly loads the Node entry module from the new location after building.
- Only affects the generated startup file
- Fixes application startup after using the `esmx build` command
- Maintains compatibility with the directory structure …

fix(rspack): update node entry import path to match new exports directory structure

---

packages/router-vue/src/plugin.test.ts
packages/router-vue/src/use.test.ts
packages/router-vue/src/use.ts
packages/router-vue/src/util.test.ts
packages/router-vue/src/util.ts

**Feature Description:**
Implemented a proxy-based route reactivity system to resolve component update issues caused by route object reference changes. This improvement ensures components correctly re-render when route properties change, even when the route object reference remains stable.
**Implementation Details:**
- Added `createDependentProxy` utility function to create proxies dependent on reactive references
- Enhanced `useProvideRouter` function to wrap router and route objects with proxies
- Trigger related component re-renders on route changes by toggling a boolean dependency value
- Optimized `useLink` function by removing unnecessary route access code
**Testing:**
- Added specific tests for reactive routing
- Verified automatic view updates when route properties change
- …

fix(router-vue): improve route reactivity with proxy implementation

---

packages/core/src/core.ts

**Issue Description:**
In server-side rendering environments, the `getFile` function in `getImportMap` was not using `fs.realpathSync` to resolve symbolic links, causing inconsistency with the `getScope` function's path handling and resulting in import map module resolution failures at runtime.
**Implementation Details:**
- Added consistent symlink resolution logic to the `getFile` function using `fs.realpathSync`
- Ensures both `getScope` and `getFile` functions return real physical paths
- Maintains consistency with the fix introduced in PR #120
- Added comprehensive English comments explaining the necessity of the fix
**Testing:**
All existing tests pass (58 test cases), ensuring backward compatibility and no regression in existing functionality.
**Potential Impact:**
This change only …

fix(core): resolve symlinks in getFile function for server import maps

---

examples/docs/src/en/api/core/module-config.md
examples/docs/src/en/guide/essentials/_meta.json
examples/docs/src/en/guide/essentials/alias.md
examples/docs/src/en/guide/essentials/module-linking.md
examples/docs/src/en/guide/start/introduction.md
examples/docs/src/en/index.md
examples/docs/src/zh/guide/essentials/_meta.json
examples/docs/src/zh/guide/essentials/alias.md
examples/docs/src/zh/guide/essentials/module-linking.md
examples/docs/src/zh/guide/start/glossary.md
examples/docs/src/zh/guide/start/introduction.md
examples/ssr-html/src/views/about.ts
examples/ssr-vue2-host/README.md
examples/ssr-vue2-host/src/app.vue
examples/ssr-vue2-host/src/entry.server.ts
examples/ssr-vue2-remote/README.md
examples/ssr-vue2-remote/src/app.vue
examples/ssr-vue2-remote/src/entry.server.ts
packages/core/README.md
packages/core/src/module-config.ts
packages/rspack-module-link-plugin/README.md

**Feature Description:**
Unify terminology across framework documentation and examples by updating "Module Link" to "Module Linking".
**Implementation Details:**
- Renamed module-link.md files to module-linking.md in both English and Chinese documentation
- Updated corresponding entries in navigation config files (_meta.json)
- Corrected terminology usage in documentation and example code
- Maintained consistency of "模块链接" in Chinese documentation, with English terms only where necessary (e.g., glossary)
- Fixed incorrect file references in example projects (expose.ts → entry.node.ts)
**Testing:**
Verified link correctness and content consistency through local documentation builds.
**Potential Impact:**
This change only affects terminology in documentation and examples, with no impact on …

docs: unify Module Link to Module Linking terminology

---

packages/create-esmx/package.json
packages/create-esmx/src/cli.ts
packages/create-esmx/src/index.ts

Added a dedicated CLI entry point to fix the issue where the `npm create esmx@latest` command was not executing properly.
- Created a dedicated `src/cli.ts` file as the CLI entry point that directly executes the `createProject()` function
- Modified the `bin` configuration in `package.json` to point to the new `dist/cli.mjs` file
- Removed the conditional logic from `index.ts` (`import.meta.url === file://${process.argv[1]}`), which might not be satisfied in the `npm create` command execution environment
Chose to create a dedicated CLI entry point file instead of modifying the conditional logic for the following reasons:
1. Provides a clearer and more reliable execution path
2. Adheres to the principle of separation of concerns
3. The dedicated CLI file handles command execution, while …

fix(create-esmx): add dedicated CLI entry point for npm create command

---

examples/router-demo/ssr-npm-base/package.json
examples/router-demo/ssr-npm-vue2/package.json
examples/router-demo/ssr-npm-vue3/package.json
examples/router-demo/ssr-share/package.json
packages/create-esmx/src/utils/template.test.ts
packages/create-esmx/template/vue2/package.json

**Feature Description:**
Standardize start scripts across all packages and example projects, ensuring they all use the same format "start": "NODE_ENV=production node dist/index.mjs".
**Implementation Details:**
- Added standard start command to 4 packages that were missing it
- Modified non-standard start command in Vue2 template package
- Updated example code in related test files
- Ensured all packages and example projects use the same start command format
**Testing:**
Verified all modifications through code review and Git diff.
**Potential Impact:**
This change affects project template generation and how example projects are started, making them consistent with other projects.

fix(scripts): standardize start scripts across all packages

---

packages/rspack-module-link-plugin/package.json
packages/rspack-module-link-plugin/src/external.ts
packages/rspack/package.json
pnpm-lock.yaml

Update @rspack/core from 1.4.6 to 1.4.8
Fixed type compatibility issue in rspack-module-link-plugin for getResolve callback parameter type change
- All unit tests pass (1000+ tests)
- System tests pass with full build verification
- Coverage reports generated successfully
- All packages build successfully

chore(packages): update @rspack/core to 1.4.8

---

packages/core/src/cli/cli.ts
packages/core/src/utils/resolve-path.test.ts
packages/core/src/utils/resolve-path.ts

- Add resolveImportPath function to fix import path compatibility issues on Windows
- Use pathToFileURL to convert local paths to reliable URL strings, ensuring cross-platform consistency
- All unit tests pass, validating correct behavior with different path formats

fix(core): fix import path compatibility on Windows

---

packages/import/src/import-vm.ts

Fixed Windows path compatibility issue by replacing  with  to handle Windows file system paths correctly
The  function properly converts Windows file paths (like C:\path\to\file.js) to standard file:// URLs, preventing  errors on Windows systems
- Unit tests pass
- TypeScript type checking passes  
- Linting passes
- All workspace tests successful

fix(import): resolve Windows fileURLToPath path conversion error

---

examples/router-demo-vue2/src/create-app.ts
packages/router/src/index.ts
packages/router/src/route.ts

Re-export deprecated types and properties:
- `RouterInstance` = `Router`
- `RouterRawLocation` = `RouteLocationInput`
- `RouterLocation` = `Route`
- `Route.pathname` = `Route.url.pathname`
- `Route.href` = `Route.url.href`

feat(router): re-export deprecated types and properties for backward compatibility

---

packages/router/src/index.ts

- Fix RouterLocation mapping to RouteLocation instead of Route
- Add missing RouteRecord deprecated type
- Clean up imports and remove outdated comments
BREAKING CHANGE: None (backwards compatible)

refactor(router): improve deprecated types export

---

packages/router/src/location.ts
packages/router/src/route.ts
packages/router/tests/route-input-resolver.test.ts

- Add `resolveRouteLocationInput` function to unify route input parsing
- Simplify Route constructor logic by removing redundant `isPlainObject` checks
- Auto-fallback to complete URL from previous route when toInput object lacks path information
- Use strict `typeof` type checking for enhanced type safety
- Support unified handling of string, object, and undefined inputs
- Use `from.href` to get complete URL (including protocol, host, pathname, search params, and hash)
- Maintain backward compatibility without affecting existing APIs
- Add 17 new unit test cases covering all usage scenarios
- All existing tests pass (872 tests + 6 todo)
- TypeScript type checking and code formatting checks pass

feat(router): add toInput resolver function to simplify Route constructor logic

---

examples/docs/package.json
examples/docs/rspress.config.ts
packages/rspack-module-link-plugin/package.json
packages/rspack/package.json
pnpm-lock.yaml

- Upgrade rspress from 2.0.0-beta.20 to @rspress/core@2.0.0-beta.22
- Upgrade @rspack/core from 1.4.8 to 1.4.9
- Remove deprecated rspress-plugin-sitemap dependency
- Handle rspress v2.0.0-beta.22 breaking changes (package rename from rspress to @rspress/core)
- Update rspress.config.ts import paths
- Remove sitemap plugin configuration
- Build tests pass
- Documentation site generates correctly
- All pages render properly

feat(dependencies): upgrade dependencies and remove deprecated packages

---

packages/router/src/route.ts
packages/router/tests/route.test.ts

Fixes route parameter replacement issue where path and fullPath were not updated when params override route parameters.
- **Fixed**: Route constructor parameter processing order
- **Refactored**: Centralized parameter replacement logic in Route constructor
- **Added**: Comprehensive test case for parameter replacement validation
- **Updated**: URL object pathname correctly with parameter replacement
Fixes route parameter replacement issue where:
- Input: `/user/0/detail` with params `{ id: 1000 }`
- Expected: `/user/1000/detail`
- Actual: `/user/0/detail` (before fix)

fix(router): resolve route parameter replacement issue

---

packages/core/src/module-config.ts
packages/rspack/src/rspack/pack.test.ts
packages/rspack/src/rspack/pack.ts

Refactored `packages/rspack/src/rspack/pack.ts` to extract two core functions and add comprehensive unit test coverage.
- Extracted `generateExports` function for manifest exports generation as a pure function
- Extracted `contentHash` function for content hashing with configurable algorithm support  
- Added comprehensive unit tests with 10 test cases
- **Type Safety**: Added precise `GenerateExportsOptions` interface type
- **Bug Fix**: Fixed `contentHash` function algorithm parameter being hardcoded to sha256
- **Test Coverage**: Achieved 100% code coverage for refactored functions
- `packages/rspack/src/rspack/pack.ts`: Refactored and exported `generateExports` and `contentHash` functions
- `packages/rspack/src/rspack/pack.test.ts`: Standardized test file name with complete test cases …

refactor(pack): extract generateExports and contentHash functions with full test coverage

---

packages/router/src/location.ts
packages/router/tests/location.test.ts
packages/router/tests/router-link.dom.test.ts

This PR fixes the protocol-relative URL handling in the router package to use the base URL's protocol instead of hardcoding `http://`. 
Previously, protocol-relative URLs (e.g., `//example.com/path`) were always resolved using `http://` protocol, which could cause security issues and inconsistencies when the application is served over HTTPS or other protocols. 
The change ensures that protocol-relative URLs inherit the protocol from the base URL, providing better security and consistency across different deployment environments.
- **Modified `normalizeURL` function** in `src/location.ts` to use `base.protocol` instead of hardcoded `http:`
- **Updated test cases** in `tests/location.test.ts` to reflect the new behavior
- **Fixed router-link tests** in `tests/router-link.dom.test.ts` to …

fix: use base URL protocol for protocol-relative URLs

---

packages/rspack/src/rspack-html/index.ts
packages/rspack/src/rspack/app.ts
packages/rspack/src/rspack/config.ts
packages/rspack/src/rspack/loader.ts
packages/rspack/src/rspack/utils/rsbuild.ts

This PR cleans up Chinese comments in the rspack package to improve international collaboration and code consistency. The changes include:
- Remove meaningless comments that just repeat property names
- Translate meaningful Chinese comments to English
- Clean up comments in rspack-html, rspack/app, rspack/config, rspack/loader, and rspack/utils/rsbuild.ts
- Improve code documentation for better maintainability
None

feat: clean Chinese comments in rspack package

---

packages/rspack/src/rspack-html/index.ts

This PR enhances the asset handling rules in the Rspack HTML configuration to provide better support for various file formats and improve asset categorization.
Key changes:
- Expand image format support to include ico, apng, avif, tif, tiff, jfif, pjpeg, pjp, cur
- Separate media and audio rules for better organization and handling
- Add mov format to media rule for video files
- Add m4a and opus formats to audio rule for better audio format support
- Include ttc format in fonts rule for TrueType Collection support
- Improve asset categorization and handling with dedicated rules
N/A

feat(rspack): enhance asset handling rules

---

packages/create-esmx/template/shared-modules/package.json
pnpm-lock.yaml

This change moves the `@esmx/router` package from dependencies to devDependencies in the shared modules template. This is a configuration fix to ensure proper dependency management in the template structure.
N/A

fix(template): move router package to devdependencies

---

packages/router/src/router.ts
packages/router/src/types.ts
packages/router/tests/micro-app.dom.test.ts
packages/router/tests/navigation.test.ts

This PR enhances the router's `rootStyle` handling to improve flexibility and developer experience when creating layered routes. The changes include:
1. **Adjusted rootStyle priority in router options**: Modified the order of option merging in the Router constructor to allow preset `rootStyle` values to be properly applied when creating routes. The default rootStyle is now applied first, then overridden by user-provided options.
2. **Enhanced type definitions**: Updated the `rootStyle` type to accept `null` in addition to existing types (`Partial<CSSStyleDeclaration>` or `false`), providing more granular control over styling behavior.
3. **Comprehensive test coverage**: Added robust test cases to ensure proper handling of `null` rootStyle values in both micro-app scenarios and navigation …

feat(router): enhance rootStyle handling with null support and improved option precedence

---

.github/workflows/build.yml
.github/workflows/publish.yml
packages/router/src/matcher.ts
packages/router/src/options.ts
packages/router/src/types.ts

This PR exposes compiled routes in the router package to improve performance and provide better access to route matching logic.
- **Modified `createMatcher` function**: Updated to accept an optional `compiledRoutes` parameter to allow reusing pre-compiled routes
- **Exported `createRouteMatches` function**: Made the route compilation function publicly available for external use
- **Enhanced `RouterParsedOptions`**: Added `compiledRoutes` property to store and expose compiled route configurations
- **Optimized route compilation**: Routes are now compiled once during options parsing and reused in the matcher
- **Performance improvement**: Eliminates redundant route compilation by reusing compiled routes
- **Better API surface**: Exposes compiled routes for advanced use cases and debugging
- …

feat(router): expose compiled routes

---

.github/workflows/build.yml

Update GitHub Actions Windows runner from `windows-latest` to `windows-2022` to avoid migration issues when GitHub migrates `windows-latest` to Windows Server 2025 in September 2025.
The `windows-2022` runner will be supported until 2028, ensuring long-term build stability and avoiding potential tooling differences that may occur with the new Windows Server 2025 image.
- GitHub Actions runner migration announcement: Windows Server 2025 migration begins September 2, 2025
- Windows 2022 runner support: Maintained for the next 3 years until 2028

ci: update Windows runner to windows-2022 for stability

---

packages/core/src/index.ts
packages/core/src/manifest-json.ts
packages/rspack-module-link-plugin/src/manifest.ts
packages/rspack-module-link-plugin/src/types.ts

Remove sizes related properties and types from manifest JSON structure to simplify the interface and eliminate unnecessary size tracking.
- Remove `sizes` property from `ManifestJsonChunk` interface
- Remove `ManifestJsonChunkSizes` interface definition
- Update all related exports in core and plugin packages
- Clean up size calculation logic in rspack-module-link-plugin
N/A

feat: remove sizes from manifest json

---

packages/rspack-module-link-plugin/src/config.ts
packages/rspack-module-link-plugin/src/index.ts

This PR simplifies the Rspack module link plugin configuration by:
- Removing the dependency on  from the  function
- Simplifying the output configuration with unified module settings
- Removing production-specific library type differentiation
- Commenting out runtimeChunk and splitChunks optimizations due to Rspack issues (see: https://github.com/web-infra-dev/rspack/issues/11578)
The changes make the configuration more streamlined and easier to maintain while maintaining the same functionality.
- https://github.com/web-infra-dev/rspack/issues/11578

feat: simplify rspack module link plugin configuration

---

examples/router-demo-vue2/src/create-app.ts
examples/router-demo-vue2/src/views/home.vue
packages/router/src/options.ts
packages/router/src/route-task.ts
packages/router/src/route-transition.ts
packages/router/src/scroll.ts
packages/router/src/types.ts

Add scroll position management to router navigation
- Implement `keepScrollPosition` option in `RouteLocation` to maintain scroll position after navigation.
- Introduce scroll position utilities for saving and retrieving scroll positions.
- Update createApp and route transition logic to handle scroll restoration.

feat: add scroll position management to router navigation

---

packages/rspack-module-link-plugin/package.json
packages/rspack/package.json
pnpm-lock.yaml

This PR updates the `@rspack/core` dependency from version 1.5.4 to 1.5.7 in two packages:
- `packages/rspack-module-link-plugin/package.json`
- `packages/rspack/package.json`
The update includes corresponding lockfile updates in `pnpm-lock.yaml` to ensure dependency consistency across the workspace.
- Rspack changelog: https://github.com/web-infra-dev/rspack/releases

Update @rspack/core from 1.5.4 to 1.5.7
